# Generated by Django 3.2.19 on 2023-09-05 13:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Modelos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoria', models.CharField(max_length=255, unique=True, verbose_name='Categoría')),
                ('peso_min', models.DecimalField(decimal_places=2, max_digits=5)),
                ('peso_max', models.DecimalField(decimal_places=2, max_digits=5)),
            ],
            options={
                'verbose_name': 'categoria',
                'verbose_name_plural': 'categorias',
                'db_table': 'categoria',
            },
        ),
        migrations.CreateModel(
            name='CodifResultado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resul', models.CharField(max_length=255, verbose_name='resultado')),
                ('descripcion', models.CharField(max_length=255, verbose_name='descripción')),
            ],
            options={
                'verbose_name': 'codifresultado',
                'verbose_name_plural': 'codifresultados',
                'db_table': 'codifresultado',
            },
        ),
        migrations.CreateModel(
            name='Combate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
            ],
            options={
                'verbose_name': 'combate',
                'verbose_name_plural': 'combates',
                'db_table': 'combate',
            },
        ),
        migrations.CreateModel(
            name='Golpe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('golpe', models.CharField(max_length=255, unique=True, verbose_name='resultado')),
            ],
            options={
                'verbose_name': 'golpe',
                'verbose_name_plural': 'golpes',
                'db_table': 'golpe',
            },
        ),
        migrations.CreateModel(
            name='Pugil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255, unique=True, verbose_name='Nombre y Apellidos')),
                ('edad', models.PositiveIntegerField()),
                ('peso', models.DecimalField(decimal_places=2, max_digits=5)),
                ('categoria', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Modelos.categoria')),
                ('pais', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Modelos.pais')),
            ],
            options={
                'verbose_name': 'pugil',
                'verbose_name_plural': 'pugils',
                'db_table': 'pugil',
            },
        ),
        migrations.CreateModel(
            name='Resultado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('combate', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Modelos.combate')),
                ('pugil', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Modelos.pugil')),
                ('resultado', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Modelos.codifresultado')),
            ],
            options={
                'verbose_name': 'resultado',
                'verbose_name_plural': 'resultados',
                'db_table': 'resultado',
            },
        ),
        migrations.CreateModel(
            name='HistoricoPeso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('peso', models.DecimalField(decimal_places=2, max_digits=5)),
                ('fecha', models.DateField()),
                ('pugil', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Modelos.pugil')),
            ],
            options={
                'verbose_name': 'histpeso',
                'verbose_name_plural': 'histpesos',
                'db_table': 'histpeso',
            },
        ),
        migrations.CreateModel(
            name='ContadorGolpes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_asalto', models.PositiveIntegerField()),
                ('esquina', models.CharField(max_length=255, verbose_name='esquina')),
                ('combate', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Modelos.combate')),
                ('golpe', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Modelos.golpe')),
            ],
            options={
                'verbose_name': 'contadorgolpe',
                'verbose_name_plural': 'contadorgolpes',
                'db_table': 'contador_golpe',
            },
        ),
        migrations.CreateModel(
            name='ConfigGolpe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tecla', models.CharField(max_length=255, verbose_name='tecla')),
                ('golpe', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Modelos.golpe')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'configolpe',
                'verbose_name_plural': 'configolpes',
                'db_table': 'config_golpe',
            },
        ),
        migrations.AddField(
            model_name='combate',
            name='esquinaA',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='person', to='Modelos.pugil'),
        ),
        migrations.AddField(
            model_name='combate',
            name='esquinaR',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='person1', to='Modelos.pugil'),
        ),
        migrations.AddField(
            model_name='combate',
            name='evento',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Modelos.evento'),
        ),
    ]
