# Generated by Django 3.2.19 on 2023-09-05 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Modelos', '0002_auto_20230905_0906'),
    ]

    operations = [
        migrations.AddField(
            model_name='golpe',
            name='siglas',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='siglas'),
        ),
        migrations.AlterField(
            model_name='golpe',
            name='golpe',
            field=models.CharField(max_length=255, unique=True, verbose_name='golpe'),
        ),
    ]
