# Generated by Django 3.2.19 on 2023-09-05 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Modelos', '0004_auto_20230905_1331'),
    ]

    operations = [
        migrations.AlterField(
            model_name='golpe',
            name='efectivo',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
