# Generated by Django 3.2.19 on 2023-09-06 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Modelos', '0005_alter_golpe_efectivo'),
    ]

    operations = [
        migrations.AddField(
            model_name='pugil',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='pugiles'),
        ),
    ]
