# Generated by Django 3.2.19 on 2023-09-06 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Modelos', '0006_pugil_foto'),
    ]

    operations = [
        migrations.AddField(
            model_name='combate',
            name='nombre',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
