# Generated by Django 3.2.19 on 2023-09-07 15:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Modelos', '0007_combate_nombre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contadorgolpes',
            name='esquina',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Modelos.pugil', verbose_name='esquina'),
        ),
    ]
