# Generated by Django 3.2.19 on 2023-09-08 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Modelos', '0009_alter_pugil_edad'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pugil',
            name='peso',
            field=models.DecimalField(decimal_places=2, max_digits=5, null=True),
        ),
    ]
